name: TinyURL CI/CD

on:
  push:
    branches:
      - main
      - develop

jobs:

  build-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore Packages
      run: dotnet restore ./API

    - name: Build API
      run: dotnet build ./API --configuration Release --no-restore

    - name: Publish API
      run: dotnet publish ./API -c Release -o publish

  build-ui:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: |
        cd UI
        npm install

    - name: Build React App
      run: |
        cd UI
        npm run build
